### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by swedneck** [ActuallyLinkhe/justflax#1]
I have double checked that the crash only happens with this mod enabled, i haven't done any further testing.

Log: https://mclo.gs/dqGNG3e

**Comment by ActuallyLinkhe** [comment]
forgor to answer but i am looking into this, this the first minecraft mod i make so i am very much not aware of what i did wrong and am trying to fix it, might take a bit

**Comment by ActuallyLinkhe** [comment]
newbie issues, fixed on commit [5689203](https://github.com/ActuallyLinkhe/justflax/commit/56892032b41be4614e1530331c3a81706bc23fb2)
