### ISSUE TITLE
fix plan

### ISSUE THREAD

**Issue by nanananona** [ActuallyLinkhe/justflax#2]
This is a proposed fix for this mod.
Currently this mod only works with Forge 47.3.10 or later.
This is because of the major changes made to Forge bordering on this version.
My fix is to make it work with earlier versions of Forge. 
The same is true for swedneck's crash and Nirahiel's crash on curseforge.

First,

Overload the following constructor in JustFlax.java

    public JustFlax() {
        this(FMLJavaModLoadingContext.get());
    }

This is the constructor in Forge 47.3.10 and earlier.
By adding this, it is possible to support both with little modification to the current source.
This way it is possible to support both versions before and after 47.3.10 with very little modification to the current source.

The following is important.
"gradlew rundata" once before running "gradlew build".
This is automatically generated by Forge in Forge 47.3.10 and later,
In earlier versions, it must be generated by the developer and included in the jar package.
(“json” is automatically created based on the java in 'datagen' package. If you rewrite the contents of 'datagen', run "rundata" again)

If you run "build" after running "rundata", the generated json will be automatically included in the package.

The generated mod will work with versions prior to Forge 47.3.10.

**Comment by ActuallyLinkhe** [comment]
you cannot believe how stupid i feel rn like i could not for the love of god find out how to do this

anyways newbie issues, fixed on commit [5689203](https://github.com/ActuallyLinkhe/justflax/commit/56892032b41be4614e1530331c3a81706bc23fb2)
